networks:
 default:
    driver: bridge
    name: roboshop
    external: true
services:
  mongodb:
    image: spandanaerukulla/mongodb:v1
    container_name: mongodb
  catalogue:
    image: spandanaerukulla/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: spandanaerukulla/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis
  cart:
    image: spandanaerukulla/cart:v1
    container_name: cart
    depends_on:
      - catalogue
      - redis
  mysql:
    image: spandanaerukulla/my-sql:v1
    container_name: mysql
  shipping:
    image: spandanaerukulla/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  # payment:
  #   image: spandanaerukulla/payment:v1
  #   container_name: payment
  #   environment:
  #      CART_HOST: cart
  #      CART_PORT: 8080
  #      USER_HOST: user
  #      USER_PORT: 8080
  #      AMQP_HOST: rabbitmq
  #      AMQP_USER: roboshop
  #      AMQP_PASSWORD: roboshop123
  #   depends_on:
  #     - rabbitmq
  #     - cart
  #     - user
  # frontend:
  #   image: spandanaerukulla/frontend:v1
  #   container_name: frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - catalogue
  #     - user
  #     - cart
  #     - shipping
  #     - payment