FROM mongo:7.0  
COPY *.js /docker-entrypoint-initdb.d













#using the official MongoDB image
# This Dockerfile is used to create a MongoDB container with initialization scripts.
# Copying initialization scripts to the appropriate directory
# MongoDB will execute these scripts on the first startup

