





# here we dont have any installantion and don't need image so
# we are directly installed the redis form dockerhub so directly using the image from dockerhub
# so just i run the command in the foregrounddocker command= docker run -d --name redis --network roboshop redis:7
#by running that command redis is pulled from docker hub and installed in the container
# so we are not using any dockerfile here
